# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotName', models.CharField(max_length=200)),
                ('currentCar', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='availabletime',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability.Spot'),
        ),
    ]
