# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20180527_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='isAvailableNow',
            field=models.BooleanField(default=True),
        ),
    ]
