# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-27 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_spot_isavailablenow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='spotName',
            new_name='spotID',
        ),
    ]
