# Generated by Django 2.0.5 on 2018-06-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_auto_20180527_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='reservedCar',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
