# Generated by Django 2.0.5 on 2018-06-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_spot_reservedcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
